{
 "title": "Dispel",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(goconsensus_client_request_latency_count[30s])\n",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(rate(goconsensus_client_request_latency_count[30s]))",
     "legendFormat": "Total TPS"
    }
   ]
  },
  {
   "title": "Go Consensus",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(goconsensus_client_request_latency_sum[30s])/rate(goconsensus_client_request_latency_count[30s])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(goconsensus_client_request_latency_bucket[30s]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(goconsensus_server_command_batch_size_sum[30s]))/avg(rate(goconsensus_server_command_batch_size_count[30s]))",
     "legendFormat": "Batch Size"
    }
   ]
  }
 ]
}